name: Iron Friends
favicon: null
layout_spectrum: 0
typography_spectrum: 0.4279475889634341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#161616'
    - '#ffffff'
    - '#a1a1a1'
    - '#3f3f3f'
    - '#d3d3d3'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
